# Generated by Django 6.0.1 on 2026-01-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('service', models.CharField(max_length=100)),
                ('log_level', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
