# Generated by Django 5.2.8 on 2026-01-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_level',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='service',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
