# Generated by Django 5.2.8 on 2026-01-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_logentry_log_level_alter_logentry_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('log_level', models.CharField(blank=True, max_length=20, null=True)),
                ('message_contains', models.CharField(blank=True, max_length=255, null=True)),
                ('email_recipients', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
